### ISSUE TITLE
cwmcu-wake-lock

### ISSUE THREAD

**Issue by pou-chi** [Lightwars/android_kernel_zte_p839f30#1]
Installed the latest version. Phone is not asleep. Almost always active.
Betterbatterystats shows that problem is cwmcu-wake-lock.
Please disable it like krab_mozga did.
Here is more details [http://www.modaco.com/forums/topic/375809-compiling-kernel-from-sources/](url)

**Comment by Lightwars** [comment]
For me the problem do not show up, see the attached pic. My device is deep sleeping most of the time.

![screenshot_2017-01-02-08-24-18 1](https://cloud.githubusercontent.com/assets/1655140/21585708/44bd0b8c-d0c6-11e6-95dc-d82754a7cc24.png)

But you could use the other kernel no one is stopping you.

**Comment by pou-chi** [comment]
May be blade s6 have multiple revisions or hardware failure, but stock has same problem for me.

I'm trying to build you kernel, but wifi isn't working.
Any tips?

P.S. And after commenting a few strings at drivers/misc/zte-sensor/CwMcuSensor.c wakelock has gone.

**Comment by Lightwars** [comment]
Not sure whats up with the wake locks...
After merging in F2FS support wifi has stopped working, I think the modul is no more functional with that modified kernel. Just a guess... You could help find out what is wrong. But maybe just enabling building the wifi modul with the kernel could solve this.

**Comment by pou-chi** [comment]
By the way, don't you have problem with adb connection to the phone?

**Comment by Lightwars** [comment]
Nope, haven't got any. You have to install the right drivers, this could be tricky.
But then it is okay.

**Comment by pou-chi** [comment]
Yes, reverting kernel to 27 Oct solves the wifi problem, thanks.
My linux development skill isn't enough to find out what is wrong with head version.

**Comment by Lightwars** [comment]
Hey @pou-chi, the CwMcu is apparently a controller, which has a firmware.
Maybe different Firmware version behave differently, can you check yours.

I think adb connection isn't really working for you, but if you have a terminal, please type:
`su`
`cat sys/devices/soc.0/78b6000.i2c/i2c-0/0-003a/input/input0/version`
or open that file in the file browser. 
My Version is 2.8

**Comment by pou-chi** [comment]
My is 2.4

**Comment by Lightwars** [comment]
Okay, thanks. 
So we do not know how much impact the versions have on the wake lock of the device...
We have to define the right sepolicy domain, so that firmware updates of the CwMcu is possible. I had tested the firmware update service beforehand, but I got sepolicy domain error.
